version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - ${VITE_BACKEND_PORT}:3000
    depends_on:
      - database
    volumes:
      - ./backend:/app
    env_file:
      - .env

  database:
    image: mysql:latest
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - .docker/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
